# Generated by Django 4.1.7 on 2023-02-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Продукт')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('image', models.CharField(max_length=3000, verbose_name='Ссылка на фото')),
                ('category', models.CharField(choices=[('food', 'Еда'), ('clothes', 'Одежда'), ('other', 'Разное')], default='other', max_length=20, verbose_name='Категория')),
                ('remainder', models.PositiveIntegerField(verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
            ],
            options={
                'ordering': ['category', 'product'],
            },
        ),
    ]
